"""empty message

Revision ID: 22c8e911ede7
Revises: 1b6d0a3fdbd2
Create Date: 2022-11-17 21:33:34.960095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c8e911ede7'
down_revision = '1b6d0a3fdbd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
