"""empty message

Revision ID: 4d8dd73bc88a
Revises: 1c9a24a43247
Create Date: 2022-11-17 21:32:07.959955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8dd73bc88a'
down_revision = '1c9a24a43247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('Accompanying')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Accompanying', sa.BLOB(), nullable=False))

    # ### end Alembic commands ###
