"""empty message

Revision ID: 87b490bcb55b
Revises: 22c8e911ede7
Create Date: 2022-11-17 21:36:55.916624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b490bcb55b'
down_revision = '22c8e911ede7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=50), nullable=True))
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passenger', schema=None) as batch_op:
        batch_op.alter_column('package_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('sex')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
